### ISSUE TITLE
Drone

### ISSUE THREAD

**Issue by haoranD** [sieuwe1/AR-Drone#1]
Hi, excellent Job!!

Can I ask what drone is it? DJI or self-DIY?

Thank you.

**Comment by sieuwe1** [comment]
Hi HoaranD

Thanks!

It is a AR-Drone 2.0 from parrot. like this one:
https://www.parrot.com/global/drones/parrot-ardrone-20-elite-edition

Any edition is fine

greetings Sieuwe

**Comment by haoranD** [comment]
Thanks! 

Have a nice day
