### ISSUE TITLE
Controller algorithms testing on parrot drones

### ISSUE THREAD

**Issue by zainab111** [sieuwe1/AR-Drone#6]
Hi Sieuwe,
I saw your work on parrot AR drone , it was amazing.
I want  to redesign the controller of parrot and test control algorithms like Optimal controllers and Fault tolerant controllers. Is it possible because I heard that the firmware of parrot is not customizable?

**Comment by sieuwe1** [comment]
Hi 

Firmware for parrot drones is not open source. Maybe build your own drone with a phixhawk controller. This one is much more advanced than that from parrot and has a easy to use sdk to control parameters deep inside the firmware for control.

**Comment by zainab111** [comment]
Thank you for your feedback.
